version: '2'
services:
    gateway:
        build: gateway/
        ports:
            - "8000:8000"
        expose:
            - 8000
        entrypoint: ./gateway config.yml
    users:
        build: users/
        ports:
            - "8081:8081"
        expose:
            - 8081
        depends_on:
            - gateway
        entrypoint: ./users config.yml
        links:
            - gateway
            - rethinkdb
    # mysql:
    #   image: mysql:5.6.26
    #   environment:
    #    - MYSQL_ROOT_PASSWORD=root
    #    - MYSQL_DATABASE=password
    #   ports:
    #     - "3306:3306"
    #   expose:
    #     - 3306
    rethinkdb:
        image: rethinkdb
        ports:
            - "8080"
            - "28015"
            - "29015"
