gateway:
    addr: gateway:8000
    protocol: http
service:
    name: users
    port: 8081
    version:
        name: alpha
        major: 1
        minor: 1
        patch: 0
database:
    host: 127.0.0.1
    port: 32772
